### ISSUE TITLE
Add .kerrhau

### ISSUE THREAD

**Issue by emmiegit** [strinking/mawabot#24]
The `.kerrhau` command will take a series of words, and then output each on its own line, with the last word split at the last character

Examples:
```
.kerrhau wait why is that not working

wait
why
is
that
not
workin
g
```

```
.kerrhau no i'm kerrhau
no
i'm
kerrha
u
```

**Comment by ammongit** [comment]
🤔

**Comment by emmiegit** [comment]
We could also have it choose the number of words per line to be randomly between 1-3

**Comment by Ma-wa-re** [comment]
Done in #25
